stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install --no-interaction --prefer-dist
    - php artisan key:generate
    - vendor/bin/phpunit
  only:
    - master

deploy_production:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar global require laravel/envoy
    - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
    - envoy run deploy --commit="$CI_COMMIT_SHA"
  environment:
    name: production
    url: http://127.0.0.1
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
